# Generated by Django 3.1.7 on 2021-04-28 08:02

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default=None, max_length=200)),
                ('lname', models.CharField(default=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(default=None, max_length=200)),
                ('pri_contact_fname', models.CharField(default=None, max_length=200)),
                ('pri_contact_lname', models.CharField(default=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('sample_type', models.CharField(default=None, max_length=200)),
                ('location', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point((-45.87867, 170.49587)), srid=4326)),
                ('field_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fieldwork.fielduser')),
            ],
        ),
    ]
