# Generated by Django 3.1.7 on 2021-04-26 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fieldwork', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Elevation',
        ),
        migrations.DeleteModel(
            name='Species',
        ),
        migrations.DeleteModel(
            name='Tree',
        ),
        migrations.DeleteModel(
            name='Zipcode',
        ),
    ]
